[package]
name = "forge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "forge"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
forge-agent = { version = "0.1.0", path = "../forge-agent" }
forge-mcp = { version = "0.1.0", path = "../forge-mcp" }
forge-process = { version = "0.1.0", path = "../forge-process" }
forge-terminal = { version = "0.1.0", path = "../forge-terminal" }
forge-tui = { version = "0.1.0", path = "../forge-tui" }
futures = "0.3.34"
ratatui.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
